#!/usr/bin/env python3
"""
FRANCKY TRI-FLUX - generates docs/09a_Public_API_Generated.md from the source code.

Every public method / public field of every class and struct in
  MQL5/Include/FranckyTriFlux/Core/*.mqh      (shared Core, identical in MQL4)
  MQL5/Include/FranckyTriFlux/Platform/Platform.mqh   (MT5 platform layer; the MT4 file has the same public API)
is listed with its exact signature, so the SSOT (docs/09) can never drift from the code.

    python3 tools/gen_api_doc.py           # (re)write the file
    python3 tools/gen_api_doc.py --check   # exit 1 if the file is out of date
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
from check_core import strip  # noqa: E402

CORE = os.path.join(ROOT, "MQL5", "Include", "FranckyTriFlux", "Core")
PLATFORM = os.path.join(ROOT, "MQL5", "Include", "FranckyTriFlux", "Platform", "Platform.mqh")
OUT = os.path.join(ROOT, "docs", "09a_Public_API_Generated.md")
SKIP = ("Config.mqh", "InputEnums.mqh")      # generated from tools/ftf_spec.py (see docs/05)


def class_bodies(code):
    """yield (kind, name, base, body-without-outer-braces)"""
    for m in re.finditer(r"\b(class|struct)\s+([A-Za-z_]\w*)\s*(?::\s*public\s+(\w+))?\s*\{", code):
        i = m.end()
        depth = 1
        j = i
        while j < len(code) and depth > 0:
            if code[j] == "{":
                depth += 1
            elif code[j] == "}":
                depth -= 1
            j += 1
        yield m.group(1), m.group(2), m.group(3), code[i:j - 1]


def top_level(body):
    """body text at depth 0 only (inline method bodies removed, replaced by ';')"""
    out = []
    depth = 0
    for ch in body:
        if ch == "{":
            if depth == 0:
                out.append(";")
            depth += 1
            continue
        if ch == "}":
            depth -= 1
            continue
        if depth == 0:
            out.append(ch)
    return "".join(out)


def public_members(kind, body):
    text = top_level(body)
    access = "public" if kind == "struct" else "private"
    members = []
    # split into statements at ';' while tracking access labels
    for stmt in re.split(r";", text):
        s = stmt
        while True:
            m = re.match(r"\s*(public|private|protected)\s*:(.*)$", s, re.S)
            if not m:
                break
            access = m.group(1)
            s = m.group(2)
        s = " ".join(s.split())
        if not s or access != "public":
            continue
        if s.startswith("#"):
            continue
        members.append(s)
    return members


def main():
    files = [f for f in sorted(os.listdir(CORE)) if f.endswith(".mqh") and f not in SKIP]
    lines = ["# 09a - Public API (generated from the source code - do not edit)",
             "",
             "Generated by `python3 tools/gen_api_doc.py` from `MQL5/Include/FranckyTriFlux/Core/*.mqh` and the MT5",
             "`Platform/Platform.mqh` (the MT4 `Platform.mqh` exposes the same public methods - checked by",
             "`tools/check_core.py`). `docs/09_SSOT_Developer_Contract.md` explains the contracts; this file is the",
             "exact, always-current list of public signatures. `CConfig` (one field per input, name = input name",
             "without `Inp`) is documented in `docs/05_Input_Parameters_Reference.md`.",
             ""]
    sources = [(f, os.path.join(CORE, f)) for f in files] + [("Platform/Platform.mqh (MT5)", PLATFORM)]
    for label, path in sources:
        code = strip(open(path, encoding="utf-8", errors="replace").read())
        blocks = []
        for kind, name, base, body in class_bodies(code):
            mem = public_members(kind, body)
            if not mem:
                continue
            head = "%s %s%s" % (kind, name, (" : public " + base) if base else "")
            blocks.append((head, mem))
        free = []
        for m in re.finditer(r"(?m)^([A-Za-z_][\w]*\s+\*?\s*FTF_\w+\s*\([^)]*\))\s*\{", code):
            free.append(" ".join(m.group(1).split()))
        if not blocks and not free:
            continue
        lines.append("## " + label)
        lines.append("")
        for head, mem in blocks:
            lines.append("```cpp")
            lines.append(head)
            for x in mem:
                lines.append("   " + x + ";")
            lines.append("```")
        if free:
            lines.append("```cpp")
            lines.append("// free functions")
            for x in free:
                lines.append(x + ";")
            lines.append("```")
        lines.append("")
    text = "\n".join(lines).rstrip() + "\n"
    if "--check" in sys.argv:
        cur = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if cur != text:
            print("docs/09a_Public_API_Generated.md is OUT OF DATE - run python3 tools/gen_api_doc.py")
            sys.exit(1)
        print("docs/09a_Public_API_Generated.md up to date")
        return
    open(OUT, "w", encoding="utf-8", newline="\n").write(text)
    print("written %s (%d lines)" % (os.path.relpath(OUT, ROOT), text.count("\n")))


if __name__ == "__main__":
    main()
