//+------------------------------------------------------------------+
//|                                                        Stats.mqh |
//|  CStats - in-session statistics per engine + TOTAL               |
//|  (docs/09 section 7.3). Slot 0 = TOTAL, slots 1..3 = engines     |
//|  (FTF_ENGINE_COUNT). Every On*() call updates the engine slot    |
//|  AND the TOTAL slot. Feeds the panel, stats.csv and OnTester().  |
//|                                                                  |
//|  Definitions (docs/09 7.3 and 1.4 "setups/day" statistics):      |
//|   setup   = every signal generated by an engine (OnSetup), also  |
//|             the ones later rejected (docs/09 1.4)                |
//|   reject  = a setup refused by a filter/gate with a reason code  |
//|             (FTF_OK and CONFIRM_PENDING are NOT rejections)      |
//|   entry   = an order actually opened (OnEntry)                   |
//|   trade   = a closed position (OnClose). win: net>0, loss: net<0 |
//|             (net==0 counts as a trade, neither win nor loss)     |
//|   equity curve = cumulative closed net per slot (starts at 0),   |
//|             max drawdown = largest peak-to-trough drop (money)   |
//|  Logging source tag: "STAT". Optional logger via SetLogger().    |
//+------------------------------------------------------------------+
#ifndef FTF_STATS_MQH
#define FTF_STATS_MQH

#include <FranckyTriFlux\Core\Utils.mqh>
#include <FranckyTriFlux\Core\Logger.mqh>

#define FTF_STATS_SRC           "STAT"
#define FTF_STATS_REJ_STRIDE    64            // reason codes per slot in m_rej[] (FTF_REJ_COUNT must stay < 64)
#define FTF_STATS_REJ_SIZE      256           // (FTF_ENGINE_COUNT+1) * FTF_STATS_REJ_STRIDE
#define FTF_STATS_PF_NO_LOSS    999.0         // profit factor reported when there is profit but no loss
#define FTF_STATS_MIN_DAYS      (1.0/24.0)    // floor of elapsed days for per-day rates (1 hour)
#define FTF_STATS_OPT_PF_CAP    100.0         // OnTester PF criterion cap
#define FTF_STATS_ROBUST_PF_CAP 3.0           // robust score: PF capped at 3
#define FTF_STATS_ROBUST_DD_DIV 5.0           // robust score: divide by (1 + maxDD% / 5)

class CStats
  {
private:
   CLogger          *m_log;                         // optional (NULL = silent)
   datetime          m_start;                       // server time when statistics started
   double            m_startEquity;                 // equity at start (for max DD %)
   datetime          m_dayStart;                    // start of the current server day ("today" counters)
   datetime          m_lastSeen;                    // latest server time seen (OnDayChange / Init)
   int               m_dayChanges;                  // number of server day changes seen
   //--- counters per slot (0 = TOTAL, 1..FTF_ENGINE_COUNT = engines)
   int               m_setups[FTF_ENGINE_COUNT+1];
   int               m_rejects[FTF_ENGINE_COUNT+1];
   int               m_entries[FTF_ENGINE_COUNT+1];
   int               m_trades[FTF_ENGINE_COUNT+1];
   int               m_wins[FTF_ENGINE_COUNT+1];
   int               m_losses[FTF_ENGINE_COUNT+1];
   double            m_grossProfit[FTF_ENGINE_COUNT+1];   // sum of winning nets (>0)
   double            m_grossLoss[FTF_ENGINE_COUNT+1];     // sum of |losing nets| (positive number)
   double            m_net[FTF_ENGINE_COUNT+1];           // cumulative closed net = equity curve value
   double            m_sumDur[FTF_ENGINE_COUNT+1];        // seconds
   double            m_sumSlip[FTF_ENGINE_COUNT+1];       // points, signed (positive = adverse)
   double            m_sumLat[FTF_ENGINE_COUNT+1];        // ms
   double            m_maxLat[FTF_ENGINE_COUNT+1];        // ms
   double            m_sumSpread[FTF_ENGINE_COUNT+1];     // points at entry
   double            m_sumMae[FTF_ENGINE_COUNT+1];        // points
   double            m_sumMfe[FTF_ENGINE_COUNT+1];        // points
   double            m_peak[FTF_ENGINE_COUNT+1];          // peak of the cumulative closed net
   double            m_maxDD[FTF_ENGINE_COUNT+1];         // max peak-to-trough drop (money)
   int               m_todayTrades[FTF_ENGINE_COUNT+1];
   int               m_todayWins[FTF_ENGINE_COUNT+1];
   double            m_todayNet[FTF_ENGINE_COUNT+1];
   int               m_rej[FTF_STATS_REJ_SIZE];           // rejection count, index slot*64+reason

   //+---------------------------------------------------------------+
   //| logging helpers (cheap check before building strings: HFT)    |
   //+---------------------------------------------------------------+
   bool              LogOn(const int level)
     {
      if(CheckPointer(m_log)==POINTER_INVALID)
         return false;
      return m_log.IsEnabled(level);
     }
   void              LogMsg(const int level,const string msg)
     {
      if(!LogOn(level))
         return;
      if(level<=FTF_LOG_ERROR)
         m_log.Error(FTF_STATS_SRC,msg);
      else if(level==FTF_LOG_WARN)
         m_log.Warn(FTF_STATS_SRC,msg);
      else if(level==FTF_LOG_INFO)
         m_log.Info(FTF_STATS_SRC,msg);
      else if(level==FTF_LOG_DEBUG)
         m_log.Debug(FTF_STATS_SRC,msg);
      else
         m_log.Trace(FTF_STATS_SRC,msg);
     }

   //+---------------------------------------------------------------+
   //| index helpers                                                 |
   //+---------------------------------------------------------------+
   //--- slot for a getter: 0..FTF_ENGINE_COUNT, -1 if invalid
   int               Slot(const int e)
     {
      if(e<0 || e>FTF_ENGINE_COUNT)
         return -1;
      return e;
     }
   //--- slot for an update: engine 1..3, or 0 (TOTAL only) for an unknown engine id
   int               EngineSlot(const int engine,const string what)
     {
      if(engine>=1 && engine<=FTF_ENGINE_COUNT)
         return engine;
      LogMsg(FTF_LOG_DEBUG,what+": engine id "+IntegerToString(engine)+" is not 1.."+
             IntegerToString(FTF_ENGINE_COUNT)+" -> counted in TOTAL only");
      return 0;
     }
   //--- index into m_rej[] or -1 (guard: reason < 64, slot valid, inside 256)
   int               RejIndex(const int slot,const int reason)
     {
      if(slot<0 || slot>FTF_ENGINE_COUNT || reason<0 || reason>=FTF_STATS_REJ_STRIDE)
         return -1;
      int k=slot*FTF_STATS_REJ_STRIDE+reason;
      if(k>=FTF_STATS_REJ_SIZE)
         return -1;
      return k;
     }
   //--- safe division (0 when the denominator is 0)
   double            Div(const double a,const double b)
     {
      if(MathAbs(b)<1e-12)
         return 0.0;
      return a/b;
     }

   //+---------------------------------------------------------------+
   //| per-slot updates (called for the engine slot and for TOTAL)   |
   //+---------------------------------------------------------------+
   void              BumpReject(const int slot,const int reason)
     {
      m_rejects[slot]++;
      int k=RejIndex(slot,reason);
      if(k>=0)
         m_rej[k]++;
      else
         LogMsg(FTF_LOG_WARN,"reject reason code "+IntegerToString(reason)+" outside 0.."+
                IntegerToString(FTF_STATS_REJ_STRIDE-1)+": counted in totals, not per reason");
     }
   void              AddEntry(const int slot,const double slippagePts,const double latencyMs,const double spreadPts)
     {
      m_entries[slot]++;
      m_sumSlip[slot]+=slippagePts;
      m_sumLat[slot]+=MathMax(latencyMs,0.0);
      if(latencyMs>m_maxLat[slot])
         m_maxLat[slot]=latencyMs;
      m_sumSpread[slot]+=MathMax(spreadPts,0.0);
     }
   //--- returns true when the closed-trade max drawdown of the slot grew
   bool              AddClose(const int slot,const double net,const double durationSec,const double maePts,const double mfePts)
     {
      m_trades[slot]++;
      m_todayTrades[slot]++;
      m_net[slot]+=net;
      m_todayNet[slot]+=net;
      if(net>0.0)
        {
         m_wins[slot]++;
         m_todayWins[slot]++;
         m_grossProfit[slot]+=net;
        }
      else if(net<0.0)
        {
         m_losses[slot]++;
         m_grossLoss[slot]+=(-net);
        }
      m_sumDur[slot]+=MathMax(durationSec,0.0);
      m_sumMae[slot]+=MathMax(maePts,0.0);
      m_sumMfe[slot]+=MathMax(mfePts,0.0);
      //--- closed-trade equity curve: peak starts at 0 (= start), DD = peak - current
      if(m_net[slot]>m_peak[slot])
         m_peak[slot]=m_net[slot];
      double dd=m_peak[slot]-m_net[slot];
      if(dd>m_maxDD[slot]+1e-9)
        {
         m_maxDD[slot]=dd;
         return true;
        }
      return false;
     }
   void              ResetToday(void)
     {
      for(int i=0;i<=FTF_ENGINE_COUNT;i++)
        {
         m_todayTrades[i]=0;
         m_todayWins[i]=0;
         m_todayNet[i]=0.0;
        }
     }

   //+---------------------------------------------------------------+
   //| text helpers                                                  |
   //+---------------------------------------------------------------+
   string            SlotLabel(const int slot)
     {
      if(slot==0)
         return "TOTAL";
      return FTF_EngineCode(slot);
     }
   string            TopRejectText(const int slot,const int k)
     {
      int code=0;
      int cnt=0;
      if(!GetRejectTop(slot,k,code,cnt))
         return "";
      return FTF_ReasonStr(code)+":"+IntegerToString(cnt);
     }
   //--- recap of the server day that just ended (INFO, once per day)
   void              LogDayRecap(void)
     {
      if(!LogOn(FTF_LOG_INFO))
         return;
      string msg="day "+TimeToString(m_dayStart,TIME_DATE)+" closed:";
      for(int i=1;i<=FTF_ENGINE_COUNT;i++)
         msg+=" "+FTF_EngineCode(i)+" "+IntegerToString(m_todayTrades[i])+"t/"+
              IntegerToString(m_todayWins[i])+"w net "+FTF_D(m_todayNet[i],2)+" |";
      msg+=" TOTAL "+IntegerToString(m_todayTrades[0])+"t/"+IntegerToString(m_todayWins[0])+
           "w net "+FTF_D(m_todayNet[0],2);
      LogMsg(FTF_LOG_INFO,msg);
      LogMsg(FTF_LOG_INFO,"running totals: "+SummaryLine(0,m_lastSeen)+" | rejects "+
             IntegerToString(m_rejects[0])+" top "+TopRejectText(0,0));
     }
   //--- robust OnTester score (TOTAL): expectancy * sqrt(trades) * min(PF,3) / (1 + maxDD%/5)
   double            RobustScore(void)
     {
      double pf=MathMin(ProfitFactor(0),FTF_STATS_ROBUST_PF_CAP);
      double ddPct=MaxDrawdownPct(0);
      return Expectancy(0)*MathSqrt((double)m_trades[0])*pf/(1.0+ddPct/FTF_STATS_ROBUST_DD_DIV);
     }

public:
                     CStats(void)
     {
      m_log=NULL;
      Reset();
     }

   //--- optional logger (extra to docs/09: CStats has no logger in Init)
   void              SetLogger(CLogger *logger)
     {
      m_log=logger;
     }

   //--- zero every counter (logger kept)
   void              Reset(void)
     {
      m_start=0;
      m_startEquity=0.0;
      m_dayStart=0;
      m_lastSeen=0;
      m_dayChanges=0;
      for(int i=0;i<=FTF_ENGINE_COUNT;i++)
        {
         m_setups[i]=0; m_rejects[i]=0; m_entries[i]=0; m_trades[i]=0; m_wins[i]=0; m_losses[i]=0;
         m_grossProfit[i]=0.0; m_grossLoss[i]=0.0; m_net[i]=0.0; m_sumDur[i]=0.0;
         m_sumSlip[i]=0.0; m_sumLat[i]=0.0; m_maxLat[i]=0.0; m_sumSpread[i]=0.0;
         m_sumMae[i]=0.0; m_sumMfe[i]=0.0; m_peak[i]=0.0; m_maxDD[i]=0.0;
         m_todayTrades[i]=0; m_todayWins[i]=0; m_todayNet[i]=0.0;
        }
      for(int j=0;j<FTF_STATS_REJ_SIZE;j++)
         m_rej[j]=0;
     }

   //+---------------------------------------------------------------+
   //| docs/09 7.3 - lifecycle                                       |
   //+---------------------------------------------------------------+
   void              Init(const datetime startServerTime,const double startEquity)
     {
      Reset();
      m_start=startServerTime;
      m_lastSeen=startServerTime;
      m_startEquity=MathMax(startEquity,0.0);
      if(startServerTime>0)
         m_dayStart=FTF_DayStart(startServerTime);
      LogMsg(FTF_LOG_INFO,"statistics started at "+(startServerTime>0 ? FTF_TimeStr(startServerTime) : "(server time unknown)")+
             " | start equity "+FTF_D(m_startEquity,2)+" | slots TOTAL + "+IntegerToString(FTF_ENGINE_COUNT)+" engines");
     }

   //--- extra: start equity known later than Init (max DD % reference)
   void              SetStartEquity(const double startEquity)
     {
      m_startEquity=MathMax(startEquity,0.0);
      LogMsg(FTF_LOG_DEBUG,"start equity for DD% set to "+FTF_D(m_startEquity,2));
     }

   //+---------------------------------------------------------------+
   //| docs/09 7.3 - event feed (pipeline steps 5, 10, 11)           |
   //+---------------------------------------------------------------+
   //--- every signal generated by an engine (counted even if later rejected: docs/09 1.4)
   void              OnSetup(const int engine)
     {
      int s=EngineSlot(engine,"setup");
      if(s>0)
         m_setups[s]++;
      m_setups[0]++;
      if(LogOn(FTF_LOG_TRACE))
         LogMsg(FTF_LOG_TRACE,"setup "+SlotLabel(s)+" #"+IntegerToString(m_setups[s])+
                " (total "+IntegerToString(m_setups[0])+")");
     }

   //--- a setup refused with a reason code (FTF_OK / CONFIRM_PENDING are not rejections: docs/09 4.1)
   void              OnReject(const int engine,const int reason)
     {
      if(reason==FTF_OK || reason==FTF_REJ_CONFIRM_PENDING)
        {
         if(LogOn(FTF_LOG_TRACE))
            LogMsg(FTF_LOG_TRACE,"reject ignored for "+FTF_EngineCode(engine)+": "+FTF_ReasonStr(reason)+
                   " is not a rejection");
         return;
        }
      int s=EngineSlot(engine,"reject");
      if(s>0)
         BumpReject(s,reason);
      BumpReject(0,reason);
      if(LogOn(FTF_LOG_TRACE))
         LogMsg(FTF_LOG_TRACE,"reject "+SlotLabel(s)+" "+FTF_ReasonStr(reason)+" x"+
                IntegerToString(RejectCount(s,reason))+" | rejects "+IntegerToString(m_rejects[s])+
                "/"+IntegerToString(m_setups[s])+" setups");
     }

   //--- an order actually opened (execution quality figures of the fill)
   void              OnEntry(const int engine,const double slippagePts,const double latencyMs,const double spreadPts)
     {
      int s=EngineSlot(engine,"entry");
      if(s>0)
         AddEntry(s,slippagePts,latencyMs,spreadPts);
      AddEntry(0,slippagePts,latencyMs,spreadPts);
      if(LogOn(FTF_LOG_DEBUG))
         LogMsg(FTF_LOG_DEBUG,"entry "+SlotLabel(s)+" slip "+FTF_D(slippagePts,1)+" pts, latency "+
                FTF_D(latencyMs,1)+" ms, spread "+FTF_D(spreadPts,1)+" pts | entries "+
                IntegerToString(m_entries[s])+"/"+IntegerToString(m_setups[s])+" setups (exec "+
                FTF_D(ExecRatePct(s),1)+"%) avg slip "+FTF_D(AvgSlippagePts(s),2)+" avg lat "+
                FTF_D(AvgLatencyMs(s),1)+" max lat "+FTF_D(m_maxLat[s],1));
     }

   //--- a closed position (net = profit + commission + swap)
   void              OnClose(const int engine,const double net,const double durationSec,const double maePts,const double mfePts)
     {
      int s=EngineSlot(engine,"close");
      bool ddEng=false;
      if(s>0)
         ddEng=AddClose(s,net,durationSec,maePts,mfePts);
      bool ddTot=AddClose(0,net,durationSec,maePts,mfePts);
      if(!LogOn(FTF_LOG_INFO))
         return;
      string res=(net>0.0 ? "WIN" : (net<0.0 ? "LOSS" : "FLAT"));
      string msg="closed "+SlotLabel(s)+" "+res+" net "+FTF_D(net,2)+" dur "+FTF_D(durationSec,1)+
                 "s MAE "+FTF_D(maePts,1)+" MFE "+FTF_D(mfePts,1)+" pts | "+SummaryLine(s,m_lastSeen);
      if(s>0)
         msg+=" | TOTAL trades "+IntegerToString(m_trades[0])+" net "+FTF_D(m_net[0],2);
      msg+=" | today "+IntegerToString(m_todayTrades[s])+"t/"+IntegerToString(m_todayWins[s])+
           "w net "+FTF_D(m_todayNet[s],2);
      LogMsg(FTF_LOG_INFO,msg);
      if(ddEng)
         LogMsg(FTF_LOG_INFO,"new max closed-trade drawdown "+SlotLabel(s)+" "+FTF_D(m_maxDD[s],2)+
                " ("+FTF_D(MaxDrawdownPct(s),2)+"% of start equity)");
      if(ddTot)
         LogMsg(FTF_LOG_INFO,"new max closed-trade drawdown TOTAL "+FTF_D(m_maxDD[0],2)+
                " ("+FTF_D(MaxDrawdownPct(0),2)+"% of start equity)");
     }

   //--- call every cycle with the server time: resets "today" counters when the server day changes
   void              OnDayChange(const datetime serverTime)
     {
      if(serverTime<=0)
         return;
      if(serverTime>m_lastSeen)
         m_lastSeen=serverTime;
      if(m_start<=0)
        {
         m_start=serverTime;   // Init ran before the first server time was known
         LogMsg(FTF_LOG_DEBUG,"statistics start time set to "+FTF_TimeStr(serverTime));
        }
      datetime newDay=FTF_DayStart(serverTime);
      if(m_dayStart<=0)
        {
         m_dayStart=newDay;
         return;
        }
      if(newDay==m_dayStart)
         return;
      LogDayRecap();
      ResetToday();
      m_dayStart=newDay;
      m_dayChanges++;
      LogMsg(FTF_LOG_INFO,"new server day "+TimeToString(newDay,TIME_DATE)+": today counters reset (day change #"+
             IntegerToString(m_dayChanges)+")");
     }

   //+---------------------------------------------------------------+
   //| docs/09 7.3 - counters                                        |
   //+---------------------------------------------------------------+
   int               Setups(const int e)   { int s=Slot(e); return (s<0 ? 0 : m_setups[s]); }
   int               Rejects(const int e)  { int s=Slot(e); return (s<0 ? 0 : m_rejects[s]); }
   int               Entries(const int e)  { int s=Slot(e); return (s<0 ? 0 : m_entries[s]); }
   int               Trades(const int e)   { int s=Slot(e); return (s<0 ? 0 : m_trades[s]); }
   int               Wins(const int e)     { int s=Slot(e); return (s<0 ? 0 : m_wins[s]); }
   int               Losses(const int e)   { int s=Slot(e); return (s<0 ? 0 : m_losses[s]); }
   int               TodayTrades(const int e) { int s=Slot(e); return (s<0 ? 0 : m_todayTrades[s]); }
   int               TodayWins(const int e)   { int s=Slot(e); return (s<0 ? 0 : m_todayWins[s]); }
   double            TodayNet(const int e)    { int s=Slot(e); return (s<0 ? 0.0 : m_todayNet[s]); }

   int               RejectCount(const int e,const int reason)
     {
      int k=RejIndex(Slot(e),reason);
      if(k<0)
         return 0;
      return m_rej[k];
     }

   //+---------------------------------------------------------------+
   //| docs/09 7.3 - ratios (all guarded against division by zero)   |
   //+---------------------------------------------------------------+
   double            NetProfit(const int e)   { int s=Slot(e); return (s<0 ? 0.0 : m_net[s]); }
   double            GrossProfit(const int e) { int s=Slot(e); return (s<0 ? 0.0 : m_grossProfit[s]); }
   double            GrossLoss(const int e)   { int s=Slot(e); return (s<0 ? 0.0 : m_grossLoss[s]); }

   double            WinRatePct(const int e)
     {
      int s=Slot(e);
      if(s<0)
         return 0.0;
      return Div((double)m_wins[s]*100.0,(double)m_trades[s]);
     }
   //--- gross profit / gross loss ; no loss -> 999 if profit else 0
   double            ProfitFactor(const int e)
     {
      int s=Slot(e);
      if(s<0)
         return 0.0;
      if(m_grossLoss[s]<=0.0)
         return (m_grossProfit[s]>0.0 ? FTF_STATS_PF_NO_LOSS : 0.0);
      return m_grossProfit[s]/m_grossLoss[s];
     }
   //--- average net per closed trade (money)
   double            Expectancy(const int e)
     {
      int s=Slot(e);
      if(s<0)
         return 0.0;
      return Div(m_net[s],(double)m_trades[s]);
     }
   double            AvgWin(const int e)
     {
      int s=Slot(e);
      if(s<0)
         return 0.0;
      return Div(m_grossProfit[s],(double)m_wins[s]);
     }
   //--- negative number (average losing net)
   double            AvgLoss(const int e)
     {
      int s=Slot(e);
      if(s<0)
         return 0.0;
      return -Div(m_grossLoss[s],(double)m_losses[s]);
     }
   double            AvgDurationSec(const int e)
     {
      int s=Slot(e);
      if(s<0)
         return 0.0;
      return Div(m_sumDur[s],(double)m_trades[s]);
     }
   //--- per entry (signed: positive = adverse)
   double            AvgSlippagePts(const int e)
     {
      int s=Slot(e);
      if(s<0)
         return 0.0;
      return Div(m_sumSlip[s],(double)m_entries[s]);
     }
   double            AvgLatencyMs(const int e)
     {
      int s=Slot(e);
      if(s<0)
         return 0.0;
      return Div(m_sumLat[s],(double)m_entries[s]);
     }
   double            MaxLatencyMs(const int e)  { int s=Slot(e); return (s<0 ? 0.0 : m_maxLat[s]); }
   double            AvgEntrySpreadPts(const int e)
     {
      int s=Slot(e);
      if(s<0)
         return 0.0;
      return Div(m_sumSpread[s],(double)m_entries[s]);
     }
   double            AvgMaePts(const int e)
     {
      int s=Slot(e);
      if(s<0)
         return 0.0;
      return Div(m_sumMae[s],(double)m_trades[s]);
     }
   double            AvgMfePts(const int e)
     {
      int s=Slot(e);
      if(s<0)
         return 0.0;
      return Div(m_sumMfe[s],(double)m_trades[s]);
     }
   double            MaxDrawdownMoney(const int e) { int s=Slot(e); return (s<0 ? 0.0 : m_maxDD[s]); }
   //--- max closed-trade drawdown in % of the start equity (0 if start equity unknown)
   double            MaxDrawdownPct(const int e)
     {
      int s=Slot(e);
      if(s<0 || m_startEquity<=0.0)
         return 0.0;
      return m_maxDD[s]/m_startEquity*100.0;
     }

   //--- elapsed days since start (floor 1 hour so the first minutes do not explode the rates)
   double            Days(const datetime now)
     {
      datetime t=now;
      if(t<=0)
         t=m_lastSeen;
      double d=0.0;
      if(m_start>0 && t>m_start)
         d=(double)((long)t-(long)m_start)/86400.0;
      return MathMax(d,FTF_STATS_MIN_DAYS);
     }
   double            SetupsPerDay(const int e,const datetime now)
     {
      int s=Slot(e);
      if(s<0)
         return 0.0;
      return (double)m_setups[s]/Days(now);
     }
   double            TradesPerDay(const int e,const datetime now)
     {
      int s=Slot(e);
      if(s<0)
         return 0.0;
      return (double)m_trades[s]/Days(now);
     }
   //--- entries / setups * 100 (share of generated setups that became orders)
   double            ExecRatePct(const int e)
     {
      int s=Slot(e);
      if(s<0)
         return 0.0;
      return Div((double)m_entries[s]*100.0,(double)m_setups[s]);
     }
   //--- rejects / setups * 100
   double            RejectRatePct(const int e)
     {
      int s=Slot(e);
      if(s<0)
         return 0.0;
      return Div((double)m_rejects[s]*100.0,(double)m_setups[s]);
     }
   datetime          StartTime(void)   { return m_start; }
   double            StartEquity(void) { return m_startEquity; }

   //--- k-th most frequent rejection reason of slot e (k 0-based: 0 = most frequent).
   //    Order: count desc, then reason code asc. false if fewer than k+1 reasons were seen.
   bool              GetRejectTop(const int e,const int k,int &reason,int &count)
     {
      reason=FTF_OK;
      count=0;
      int s=Slot(e);
      if(s<0 || k<0 || k>=FTF_STATS_REJ_STRIDE)
         return false;
      int prevCnt=INT_MAX;
      int prevRsn=-1;
      for(int r=0;r<=k;r++)
        {
         int bestRsn=-1;
         int bestCnt=0;
         for(int c=0;c<FTF_STATS_REJ_STRIDE;c++)
           {
            int idx=RejIndex(s,c);
            if(idx<0)
               continue;
            int n=m_rej[idx];
            if(n<=0)
               continue;
            //--- must rank strictly after the previously selected reason
            if(!(n<prevCnt || (n==prevCnt && c>prevRsn)))
               continue;
            if(bestRsn<0 || n>bestCnt)
              {
               bestRsn=c;
               bestCnt=n;
              }
           }
         if(bestRsn<0)
            return false;
         prevCnt=bestCnt;
         prevRsn=bestRsn;
        }
      reason=prevRsn;
      count=prevCnt;
      return true;
     }

   //+---------------------------------------------------------------+
   //| docs/09 7.3 - text outputs                                    |
   //+---------------------------------------------------------------+
   //--- compact line, e.g. "MOM trades 12 WR 83.3% PF 2.10 exp 1.25 net 15.00 DD 3.20 setups/d 40.0"
   string            SummaryLine(const int e,const datetime now)
     {
      int s=Slot(e);
      if(s<0)
         return "stats: invalid engine "+IntegerToString(e);
      return SlotLabel(s)+" trades "+IntegerToString(m_trades[s])+
             " WR "+FTF_D(WinRatePct(s),1)+"%"+
             " PF "+FTF_D(ProfitFactor(s),2)+
             " exp "+FTF_D(Expectancy(s),2)+
             " net "+FTF_D(m_net[s],2)+
             " DD "+FTF_D(m_maxDD[s],2)+
             " setups/d "+FTF_D(SetupsPerDay(s,now),1);
     }

   string            CsvHeader(void)
     {
      string hdr="engine;setups;setups_per_day;entries;trades;trades_per_day;exec_rate_pct;wins;losses;";
      hdr+="win_rate_pct;profit_factor;expectancy;net_profit;gross_profit;gross_loss;avg_win;avg_loss;";
      hdr+="max_dd_money;max_dd_pct;avg_duration_s;avg_slippage_pts;avg_latency_ms;max_latency_ms;";
      hdr+="avg_mae_pts;avg_mfe_pts;rejects;reject_rate_pct;top_reject_1;top_reject_2;top_reject_3";
      return hdr;
     }

   //--- one stats.csv row for slot e (0 = TOTAL)
   string            CsvRow(const int e,const datetime now)
     {
      int s=Slot(e);
      if(s<0)
         return "";
      string sep=";";
      string row=SlotLabel(s);
      row+=sep+IntegerToString(m_setups[s]);
      row+=sep+FTF_D(SetupsPerDay(s,now),2);
      row+=sep+IntegerToString(m_entries[s]);
      row+=sep+IntegerToString(m_trades[s]);
      row+=sep+FTF_D(TradesPerDay(s,now),2);
      row+=sep+FTF_D(ExecRatePct(s),2);
      row+=sep+IntegerToString(m_wins[s]);
      row+=sep+IntegerToString(m_losses[s]);
      row+=sep+FTF_D(WinRatePct(s),2);
      row+=sep+FTF_D(ProfitFactor(s),3);
      row+=sep+FTF_D(Expectancy(s),4);
      row+=sep+FTF_D(m_net[s],2);
      row+=sep+FTF_D(m_grossProfit[s],2);
      row+=sep+FTF_D(m_grossLoss[s],2);
      row+=sep+FTF_D(AvgWin(s),4);
      row+=sep+FTF_D(AvgLoss(s),4);
      row+=sep+FTF_D(m_maxDD[s],2);
      row+=sep+FTF_D(MaxDrawdownPct(s),3);
      row+=sep+FTF_D(AvgDurationSec(s),1);
      row+=sep+FTF_D(AvgSlippagePts(s),2);
      row+=sep+FTF_D(AvgLatencyMs(s),1);
      row+=sep+FTF_D(m_maxLat[s],1);
      row+=sep+FTF_D(AvgMaePts(s),1);
      row+=sep+FTF_D(AvgMfePts(s),1);
      row+=sep+IntegerToString(m_rejects[s]);
      row+=sep+FTF_D(RejectRatePct(s),2);
      row+=sep+TopRejectText(s,0);
      row+=sep+TopRejectText(s,1);
      row+=sep+TopRejectText(s,2);
      return row;
     }

   //--- stats.csv (overwrite): "# header", column header, engines 1..3, TOTAL. ANSI text, ';' separator
   bool              WriteCsv(const string fileName,const bool useCommon,const datetime now,const string header)
     {
      if(StringLen(fileName)==0)
        {
         LogMsg(FTF_LOG_WARN,"stats.csv not written: empty file name");
         return false;
        }
      int flags=FILE_WRITE|FILE_TXT|FILE_ANSI;
      if(useCommon)
         flags|=FILE_COMMON;
      ResetLastError();
      int h=FileOpen(fileName,flags);
      if(h==INVALID_HANDLE)
        {
         //--- the folder may not exist yet: create it and retry once
         EnsureFolder(fileName,useCommon);
         ResetLastError();
         h=FileOpen(fileName,flags);
        }
      if(h==INVALID_HANDLE)
        {
         LogMsg(FTF_LOG_ERROR,"cannot write "+fileName+(useCommon ? " (Common\\Files)" : "")+
                " error "+IntegerToString(GetLastError()));
         return false;
        }
      string title=header;
      StringReplace(title,"\r"," ");
      StringReplace(title,"\n"," ");
      FileWriteString(h,"# "+title+"\r\n");
      FileWriteString(h,CsvHeader()+"\r\n");
      for(int i=1;i<=FTF_ENGINE_COUNT;i++)
         FileWriteString(h,CsvRow(i,now)+"\r\n");
      FileWriteString(h,CsvRow(0,now)+"\r\n");
      FileClose(h);
      LogMsg(FTF_LOG_INFO,"stats written to "+fileName+(useCommon ? " (Common\\Files)" : "")+" | "+
             SummaryLine(0,now)+" | rejects "+IntegerToString(m_rejects[0])+" top "+TopRejectText(0,0));
      return true;
     }

   //--- creates the folder part of a relative file path (FolderCreate is recursive in MQL4/MQL5)
   void              EnsureFolder(const string fileName,const bool useCommon)
     {
      string path=fileName;
      StringReplace(path,"/","\\");
      int cut=-1;
      int len=StringLen(path);
      for(int i=len-1;i>=0;i--)
        {
         if(StringGetCharacter(path,i)=='\\')
           {
            cut=i;
            break;
           }
        }
      if(cut<=0)
         return;
      string folder=StringSubstr(path,0,cut);
      ResetLastError();
      bool ok=FolderCreate(folder,(useCommon ? FILE_COMMON : 0));
      if(ok)
         LogMsg(FTF_LOG_DEBUG,"folder ready: "+folder);
      else
         LogMsg(FTF_LOG_WARN,"FolderCreate("+folder+") failed, error "+IntegerToString(GetLastError()));
     }

   //+---------------------------------------------------------------+
   //| docs/09 7.3 - OnTester value (TOTAL slot)                     |
   //+---------------------------------------------------------------+
   //--- 0.0 when trades < minTrades (invalid optimisation pass)
   double            OptCriterion(const int criterion,const int minTrades)
     {
      string name=EnumToString((ENUM_FTF_OPT_CRITERION)criterion);
      int n=m_trades[0];
      if(n<minTrades || n<=0)
        {
         LogMsg(FTF_LOG_INFO,"OnTester "+name+" = 0 (trades "+IntegerToString(n)+" < min "+
                IntegerToString(minTrades)+")");
         return 0.0;
        }
      double v=0.0;
      switch(criterion)
        {
         case FTF_OPT_NET_PROFIT:
            v=m_net[0];
            break;
         case FTF_OPT_PROFIT_FACTOR:
            v=MathMin(ProfitFactor(0),FTF_STATS_OPT_PF_CAP);
            break;
         case FTF_OPT_EXPECTANCY:
            v=Expectancy(0);
            break;
         case FTF_OPT_WINRATE:
            v=WinRatePct(0);
            break;
         case FTF_OPT_ROBUST:
            v=RobustScore();
            break;
         default:
            LogMsg(FTF_LOG_WARN,"unknown optimisation criterion "+IntegerToString(criterion)+" -> robust score");
            v=RobustScore();
            break;
        }
      LogMsg(FTF_LOG_INFO,"OnTester "+name+" = "+FTF_D(v,4)+" | "+SummaryLine(0,m_lastSeen)+
             " | maxDD% "+FTF_D(MaxDrawdownPct(0),2));
      return v;
     }
  };

#endif // FTF_STATS_MQH
